---
title: "Homework 5"
author: "Jessica Lavery, MS"
date: "Due 11/11/2019"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
set.seed(10)

```

## Problem 1

```{r}
# load iris dataset from tidyverse package and introduce missing values
iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))

# write a function to replace missing values per pre-defined rules
# numeric variables, fill in missing with the mean of non-missing



# create input list of variable names
input <- names(iris_with_missing)

# create output vector to store result of function
output <- vector("list", length = length(input))

replace_missing <- function(x) {
  if (is.numeric(x)) {
    new_value = mean(x, na.rm = TRUE)
    
  }  else if (is.character(x)) {
    new_value = "virginica"
  }
  
  # return vector
  tibble(pull(iris_with_missing, x) = 
    mutate(x = case_when(!is.na(x) ~ new_value,
                         TRUE ~ x))
}

output = map(iris_with_missing, replace_missing)
output
```

